name: socialgist
description: SocialGist

version: 0.0.15+15

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # https://pub.dev/packages/intl
  intl: 0.16.1
  # https://pub.dev/packages/http
  http: 0.12.1
  # https://pub.dev/packages/url_launcher
  url_launcher: 5.4.10
  # https://pub.dev/packages/shared_preferences
  shared_preferences: 0.5.7+3
  # https://pub.dev/packages/google_fonts
  google_fonts: 1.0.0 # Error 1.1.0
  # https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: 8.8.1
  # https://pub.dev/packages/flutter_highlight
  flutter_highlight: 0.6.0
  # https://pub.dev/packages/i18n_extension
  i18n_extension: 1.3.7
  # https://pub.dev/packages/share
  share: 0.6.4+3
  # https://pub.dev/packages/firebase_analytics
  firebase_analytics: 5.0.11
  # https://pub.dev/packages/firebase_crashlytics
  firebase_crashlytics: 0.1.3+3

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  # https://pub.dev/packages/screenshots
  screenshots: 2.1.1
  # https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: 0.7.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/socialgist-logo-full.png
