name: socialgist
description: Socialgist.

version: 0.0.8+8

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # https://pub.dev/packages/intl
  intl: 0.16.1
  # https://pub.dev/packages/http
  http: 0.12.1
  # https://pub.dev/packages/url_launcher
  url_launcher: 5.4.5
  # https://pub.dev/packages/shared_preferences
  shared_preferences: 0.5.7+1
  # https://pub.dev/packages/google_fonts
  google_fonts: 1.0.0 # Error 1.1.0
  # https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: 8.8.1
  # https://pub.dev/packages/flutter_highlight
  flutter_highlight: 0.6.0
  # https://pub.dev/packages/i18n_extension
  i18n_extension: 1.3.6

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  # https://pub.dev/packages/screenshots
  screenshots: 2.1.1
  # https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: 0.7.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/web_hi_res_512.png
