name: socialgist
description: Socialgist.

version: 0.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # https://pub.dev/packages/intl
  intl: 0.16.1
  # https://pub.dev/packages/http
  http: 0.12.0+4
  # https://pub.dev/packages/url_launcher
  url_launcher: 5.4.2
  # https://pub.dev/packages/shared_preferences
  shared_preferences: 0.5.6+3
  # https://pub.dev/packages/google_fonts
  google_fonts: 0.4.0
  # https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: 8.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
